### ISSUE TITLE
"Too many open files" error triggered after sending 1000 requests.

### ISSUE THREAD

**Issue by shulard** [php-http/socket-client#44]
Hello,

I tried to use the `socket-client` to upload some data on a server. I've a basic implementation which create a client and inside a foreach loop, I make the upload requests using the Guzzle PSR7 message factory.

```php
foreach ($iterator as $splfileinfo) {
    $response = $this->httpClient()->sendRequest(
        $request = $this->requestFactory()->createRequest(
            'POST',
            $sendUrl,
            $headers,
            $splFileInfo->openFile('r')
        )
    );
}
```

After 1007 successful requests, I got the `Too many open files` error and it seems that's the number of opened socket by the client. Is it normal that the socket connexion is never closed after the request is successfully sent (maybe I miss something 😄) ?

**Comment by joelwurtz** [comment]
Does the response returns a body ?

This client always stream the body (which means it never read the underlying socket after headers have been received) so maybe it's because you never consume the body returned by the response ?

You can also try to manually close the socket after the reponse has been received by calling $request->getBody()->close();

**Comment by joelwurtz** [comment]
Closing this, as it seems to be mainly a problem of not reading the response body (so error is "normal")
