### ISSUE TITLE
How to do a POST request using this socket-client library ?

### ISSUE THREAD

**Issue by vaibhavatul47** [php-http/socket-client#7]
All the examples in `test` are only for GET method. When I tried doing a POST request without any data it succeeded, but if I add data in form of String or PHP array, it throws a NetworkException exception saying, 'Cannot read the response'

**Comment by joelwurtz** [comment]
There is also POST request with data who works well in the tests.

Be aware that this library make the assumption that your request is a valid one, so if you send data with a post request you also need to have the correct `Content-Length` header in your request, otherwise server will believe that the request has no body.

If you need to add those behavior automatically (add the content length header), i recommend you to check the plugins repository.
